services:
  - type: web
    name: meetapp
    env: node
    region: oregon
    plan: free
    buildCommand: bash build.sh
    startCommand: cd API && npm start
    envVars:
      - key: NODE_ENV
        value: production
